sudo: required
language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - nvm install node
  - nvm alias default node
  - npm install
  - scripts/setup_heroku.sh
  - git clone $TEST_SITE_GIT_REMOTE output
before_script:
  - npm run build
  - fab publish
  - cd output && git add --ignore-removal . && git commit -m 'deploy for test' && git push origin master -f && cd -
script:
  - npm test
deploy:
  provider: pages
  local_dir: output
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
after_script:
  - heroku keys:clear

